Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
        
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.18.64", netmask: "255.255.255.0", gateway: "192.168.18.1"
end